# Generated by Django 6.0.6 on 2026-07-16 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_alter_productimage_options_productimage_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=30, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(max_length=30)),
                ('customer_document', models.CharField(max_length=30)),
                ('payment_method', models.CharField(choices=[('usdt', 'USDT'), ('zelle', 'Zelle'), ('zinli', 'Zinli'), ('paypal', 'PayPal'), ('transfer', 'Transferencia'), ('pago_movil', 'Pago Móvil'), ('cash', 'Efectivo')], max_length=30)),
                ('shipping_method', models.CharField(choices=[('pickup', 'Pick-up'), ('delivery', 'Delivery'), ('agency', 'Agencia')], max_length=30)),
                ('delivery_zone', models.CharField(blank=True, choices=[('propatria', 'Propatria'), ('perez_bonalde', 'Pérez Bonalde'), ('plaza_sucre', 'Plaza Sucre'), ('gato_negro', 'Gato Negro'), ('agua_salud', 'Agua Salud'), ('capitolio', 'Capitolio'), ('la_hoyada', 'La Hoyada'), ('parque_central', 'Parque Central'), ('nuevo_circo', 'Nuevo Circo'), ('teatros', 'Teatros'), ('plaza_venezuela', 'Plaza Venezuela'), ('sabana_grande', 'Sabana Grande'), ('chacaito', 'Chacaíto'), ('chacao', 'Chacao'), ('altamira', 'Altamira'), ('miranda', 'Miranda'), ('los_dos_caminos', 'Los Dos Caminos'), ('los_cortijos', 'Los Cortijos'), ('la_california', 'La California'), ('petare', 'Petare'), ('bello_monte', 'Bello Monte'), ('zona_rental', 'Zona Rental'), ('parque_central', 'Parque Central'), ('nuevo_circo', 'Nuevo Circo'), ('teatros', 'Teatros'), ('el_silencio', 'El Silencio'), ('capuchinos', 'Capuchinos'), ('maternidad', 'Maternidad'), ('artigas', 'Artigas'), ('la_paz', 'La Paz'), ('la_yaguara', 'La Yaguara'), ('carapita', 'Carapita'), ('antimano', 'Antímano'), ('mamera', 'Mamera'), ('caricuao', 'Caricuao'), ('zoologico', 'Zoológico'), ('ruiz_pineda', 'Ruiz Pineda'), ('las_adjuntas', 'Las Adjuntas'), ('ciudad_universitaria', 'Ciudad Universitaria'), ('los_simbolos', 'Los Simbolos'), ('la_bandera', 'La Bandera'), ('el_valle', 'El Valle'), ('los_jardines', 'Los Jardines'), ('coche', 'Coche'), ('mercado', 'Mercado'), ('la_rinconada', 'La Rinconada'), ('los_teques', 'Los Teques')], max_length=50)),
                ('agency_name', models.CharField(blank=True, choices=[('mrw', 'MRW')], max_length=20)),
                ('agency_address', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
        ),
    ]
